name: 'Reset Supabase Database'
description: 'Clean an Supabase database and reset it to a blank state'
inputs:
  connectionString:  # id of input
    description: 'e.g. postgres://user:password@host:5432/database'
    required: true
runs:
  using: 'node16'
  main: 'dist/index.mjs'
