name: 'Reset Supabase Database'
description: 'Clean an Supabase database and reset it to a blank state'
inputs:
  connectionString:  # id of input
    description: 'e.g. postgres://user:password@host:5432/database'
    required: true
  users:  # id of input
    description: 'List if user emails to delete e.g. test@test.com,test2@test.com'
    required: false 
  buckets:  # id of input
    description: 'List of buckets to delete e.g. public,content'
    required: false 
runs:
  using: 'node16'
  main: 'dist/index.js'
